### ISSUE TITLE
Need null safety support

### ISSUE THREAD

**Issue by Basher7** [kkazuo/azblob#1]
**from flutter v2.0.2, flutter is now null-safety mechanism. Most of the packages already upgrade to null safety and more are upgrading.**

Thanks for this great package!

_Do you plan to make a null safe version of the package and publish to pub?_

**Comment by kkazuo** [comment]
yes!
And now supports null-safety.
https://pub.dev/packages/azblob

Please feel free to post new issue if you have found something.

**Comment by Basher7** [comment]
Thanks for null safety version.
One more help, could you please add GitHub repo link in [pub.dev](https://pub.dev/packages/azblob) for this plugin?
So that people can find easily.

**Comment by kkazuo** [comment]
Good point.

I will add this link to pubspec.yaml next release.
https://github.com/kkazuo/dart-azblob

Actualiy, this repo is OCaml version of azblob, not Dart. :)

**Comment by Basher7** [comment]
I didn't notice that. Thanks after all.
